name: Unit Tests

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    php73:
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP 7.3
              uses: shivammathur/setup-php@master
              with:
                  php-version: '7.3'
                  extensions: gd, intl, xsl, zip, pdo, pdo_mysql, soap, bcmath, sodium
                  tools: composer:v1, prestissimo
            - name: Install composer dependencies
              run: |
                  composer global config http-basic.repo.magento.com ${{ secrets.MAGENTO_PUBLIC_KEY }} ${{ secrets.MAGENTO_PRIVATE_KEY }}
                  composer install --prefer-dist --no-interaction --no-progress --no-suggest
            - name: Run phpunit
              run: |
                  ./vendor/bin/phpunit --testdox --coverage-clover=/tmp/report.xml
            - name: Save code coverage report artifact
              uses: actions/upload-artifact@v2
              with:
                  name: report
                  path: /tmp/report.xml
    php74:
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP 7.4
              uses: shivammathur/setup-php@master
              with:
                  php-version: '7.4'
                  extensions: gd, intl, xsl, zip, pdo, pdo_mysql, soap, bcmath, sodium
                  tools: composer:v1, prestissimo
            - name: Install composer dependencies
              run: |
                  composer global config http-basic.repo.magento.com ${{ secrets.MAGENTO_PUBLIC_KEY }} ${{ secrets.MAGENTO_PRIVATE_KEY }}
                  composer install --prefer-dist --no-interaction --no-progress --no-suggest
            - name: Run phpunit
              run: |
                  ./vendor/bin/phpunit --testdox --coverage-clover=/tmp/report.xml
            - name: Save code coverage report artifact
              uses: actions/upload-artifact@v2
              with:
                  name: report
                  path: /tmp/report.xml
    codecov:
        runs-on: ubuntu-18.04
        needs: [php73, php74]
        steps:
            - name: Download code coverage report artifact
              uses: actions/download-artifact@v2
              with:
                  name: report
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  file: ./report.xml
                  name: codecov-report
